# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eigerQsoGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1087, 781)
        self.plotWindow = QtWidgets.QWidget(Dialog)
        self.plotWindow.setGeometry(QtCore.QRect(20, 10, 1041, 691))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWindow.sizePolicy().hasHeightForWidth())
        self.plotWindow.setSizePolicy(sizePolicy)
        self.plotWindow.setObjectName("plotWindow")
        self.plotLayout = QtWidgets.QVBoxLayout(self.plotWindow)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.SpectraSelectionPushButton = QtWidgets.QPushButton(Dialog)
        self.SpectraSelectionPushButton.setGeometry(QtCore.QRect(480, 720, 171, 32))
        self.SpectraSelectionPushButton.setAutoDefault(False)
        self.SpectraSelectionPushButton.setObjectName("SpectraSelectionPushButton")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 730, 404, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reloadPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.reloadPushButton.setAutoDefault(False)
        self.reloadPushButton.setObjectName("reloadPushButton")
        self.horizontalLayout.addWidget(self.reloadPushButton)
        self.redshiftLabel = QtWidgets.QLabel(self.layoutWidget)
        self.redshiftLabel.setObjectName("redshiftLabel")
        self.horizontalLayout.addWidget(self.redshiftLabel)
        self.redshiftEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.redshiftEdit.setObjectName("redshiftEdit")
        self.horizontalLayout.addWidget(self.redshiftEdit)
        self.vpTreePushButton = QtWidgets.QPushButton(Dialog)
        self.vpTreePushButton.setGeometry(QtCore.QRect(670, 720, 161, 32))
        self.vpTreePushButton.setAutoDefault(False)
        self.vpTreePushButton.setObjectName("vpTreePushButton")
        self.loadVPfitButton = QtWidgets.QPushButton(Dialog)
        self.loadVPfitButton.setGeometry(QtCore.QRect(860, 720, 151, 32))
        self.loadVPfitButton.setAutoDefault(False)
        self.loadVPfitButton.setObjectName("loadVPfitButton")
        self.eigerObjectSelect = QtWidgets.QComboBox(Dialog)
        self.eigerObjectSelect.setGeometry(QtCore.QRect(20, 700, 141, 26))
        self.eigerObjectSelect.setObjectName("eigerObjectSelect")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SpectraSelectionPushButton.setText(_translate("Dialog", "Select Plotted Spectra"))
        self.reloadPushButton.setText(_translate("Dialog", "Reload Spectrum"))
        self.redshiftLabel.setText(_translate("Dialog", "Absorption redshift"))
        self.vpTreePushButton.setText(_translate("Dialog", "View VPModelTree"))
        self.loadVPfitButton.setText(_translate("Dialog", "Load / View VP Fit"))
