# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineSelector(object):
    def setupUi(self, LineSelector):
        LineSelector.setObjectName("LineSelector")
        LineSelector.resize(302, 882)
        self.buttonBox = QtWidgets.QDialogButtonBox(LineSelector)
        self.buttonBox.setGeometry(QtCore.QRect(70, 820, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineListWidget = QtWidgets.QListWidget(LineSelector)
        self.lineListWidget.setGeometry(QtCore.QRect(20, 30, 261, 781))
        self.lineListWidget.setObjectName("lineListWidget")

        self.retranslateUi(LineSelector)
        self.buttonBox.accepted.connect(LineSelector.accept)
        self.buttonBox.rejected.connect(LineSelector.reject)
        QtCore.QMetaObject.connectSlotsByName(LineSelector)

    def retranslateUi(self, LineSelector):
        _translate = QtCore.QCoreApplication.translate
        LineSelector.setWindowTitle(_translate("LineSelector", "Dialog"))
