# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpecSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpectrumSelector(object):
    def setupUi(self, SpectrumSelector):
        SpectrumSelector.setObjectName("SpectrumSelector")
        SpectrumSelector.resize(260, 222)
        self.buttonBox = QtWidgets.QDialogButtonBox(SpectrumSelector)
        self.buttonBox.setGeometry(QtCore.QRect(-140, 150, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(SpectrumSelector)
        self.label.setGeometry(QtCore.QRect(60, 110, 60, 16))
        self.label.setObjectName("label")
        self.spec3ComboBox = QtWidgets.QComboBox(SpectrumSelector)
        self.spec3ComboBox.setGeometry(QtCore.QRect(120, 30, 104, 26))
        self.spec3ComboBox.setObjectName("spec3ComboBox")
        self.spec2ComboBox = QtWidgets.QComboBox(SpectrumSelector)
        self.spec2ComboBox.setGeometry(QtCore.QRect(120, 70, 104, 26))
        self.spec2ComboBox.setObjectName("spec2ComboBox")
        self.spec1ComboBox = QtWidgets.QComboBox(SpectrumSelector)
        self.spec1ComboBox.setGeometry(QtCore.QRect(120, 110, 104, 26))
        self.spec1ComboBox.setObjectName("spec1ComboBox")
        self.Spec3CheckBox = QtWidgets.QCheckBox(SpectrumSelector)
        self.Spec3CheckBox.setGeometry(QtCore.QRect(40, 30, 87, 20))
        self.Spec3CheckBox.setObjectName("Spec3CheckBox")
        self.Spec2CheckBox = QtWidgets.QCheckBox(SpectrumSelector)
        self.Spec2CheckBox.setGeometry(QtCore.QRect(40, 70, 87, 20))
        self.Spec2CheckBox.setObjectName("Spec2CheckBox")

        self.retranslateUi(SpectrumSelector)
        self.buttonBox.accepted.connect(SpectrumSelector.accept)
        self.buttonBox.rejected.connect(SpectrumSelector.reject)
        QtCore.QMetaObject.connectSlotsByName(SpectrumSelector)

    def retranslateUi(self, SpectrumSelector):
        _translate = QtCore.QCoreApplication.translate
        SpectrumSelector.setWindowTitle(_translate("SpectrumSelector", "Dialog"))
        self.label.setText(_translate("SpectrumSelector", "Plot #1"))
        self.Spec3CheckBox.setText(_translate("SpectrumSelector", "Plot #3"))
        self.Spec2CheckBox.setText(_translate("SpectrumSelector", "Plot #2"))
