# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vpModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoigtProfileModel(object):
    def setupUi(self, VoigtProfileModel):
        VoigtProfileModel.setObjectName("VoigtProfileModel")
        VoigtProfileModel.resize(607, 467)
        self.buttonBox = QtWidgets.QDialogButtonBox(VoigtProfileModel)
        self.buttonBox.setGeometry(QtCore.QRect(420, 430, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vpModelTree = QtWidgets.QTreeView(VoigtProfileModel)
        self.vpModelTree.setGeometry(QtCore.QRect(10, 10, 581, 411))
        self.vpModelTree.setObjectName("vpModelTree")
        self.vpModelTree.header().setDefaultSectionSize(200)
        self.writeButton = QtWidgets.QPushButton(VoigtProfileModel)
        self.writeButton.setGeometry(QtCore.QRect(90, 430, 81, 32))
        self.writeButton.setObjectName("writeButton")
        self.readButton = QtWidgets.QPushButton(VoigtProfileModel)
        self.readButton.setGeometry(QtCore.QRect(10, 430, 81, 32))
        self.readButton.setObjectName("readButton")
        self.clearButton = QtWidgets.QPushButton(VoigtProfileModel)
        self.clearButton.setGeometry(QtCore.QRect(170, 430, 81, 32))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(VoigtProfileModel)
        self.buttonBox.accepted.connect(VoigtProfileModel.accept)
        self.buttonBox.rejected.connect(VoigtProfileModel.reject)
        QtCore.QMetaObject.connectSlotsByName(VoigtProfileModel)

    def retranslateUi(self, VoigtProfileModel):
        _translate = QtCore.QCoreApplication.translate
        VoigtProfileModel.setWindowTitle(_translate("VoigtProfileModel", "Dialog"))
        self.writeButton.setText(_translate("VoigtProfileModel", "Write"))
        self.readButton.setText(_translate("VoigtProfileModel", "Read"))
        self.clearButton.setText(_translate("VoigtProfileModel", "Clear"))
